Initial draft on project description and purpose
marcusrettig/data-universe pull request #19
Opened 2017-05-23 10:51 UTC by johanlinaker

My initial take on the goal and purpose of the project. May serve as a foundation for further discussion and development.

2017-05-23 11:03 UTC, altaired approved these changes

2017-05-30 22:12 UTC, marcusrettig requested changes
Overall good job! See comment about changes that need to be made under ## Setup section.

2017-05-30 22:12 UTC, marcusrettig commented on README.md
> +The project is currently in an early state why it may not be ready to most end-users. However, if you have the technical background needed, and interested in setting it up, we encourage you to downlo
The framework we use is three.js, not D3.js. Also it was tested on an iPhone.

2017-06-12 14:00 UTC, johanlinaker commented
Updated the readme accordingly, please verify changes.

2017-06-12 14:32 UTC, funrep commented
Looks good! I'll just wait for Marcus to confirm he's OK having his email in the README.

2017-06-12 14:54 UTC, johanlinaker commented
An alternative is that we buy a domain and add forwarding to your email(s). We should have this discussion outside of this PR though.

2017-06-14 09:08 UTC, funrep reviewed
Good, ready to merge!

2017-06-22 11:33 UTC, funrep approved these changes

2017-06-27 13:52 UTC, marcusrettig approved these changes

2017-06-27 13:53 UTC, merged