Feature/select feedback
marcusrettig/data-universe pull request #21
Opened 2017-06-19 09:58 UTC by funrep

Added visual feedback to selection in the form of resizing the crosshair.

2017-06-25 22:11 UTC, marcusrettig commented
@funrep Nice! Do you also have time to also add a popup message? Maybe like [this](https://material.angular.io/components/snack-bar/examples) (press the button).

2017-06-26 09:48 UTC, funrep commented
@marcusrettig good idea, I should do that!

2017-06-26 09:49 UTC, funrep commented
@marcusrettig No, that's an error, closing this one and open a new.

2017-06-26 13:00 UTC, funrep commented
@marcusrettig ping, added basic pop up, realized we need to make animations FPS-independent (integrate deltatime into the calculations), also there is refactoring to be made because Popup and Billboard share a bit of code, but I'll start a new branch for those changes.

2017-06-30 19:35 UTC, funrep commented
@marcusrettig @perssonsimon1 could someone review this?

2017-06-30 23:26 UTC, marcusrettig requested changes
See line comments. Most important to fix is in `Selector.js:78`.

2017-06-30 23:26 UTC, marcusrettig commented on src/Selector.js
> +    this.selectEvent = false;
Could you name this differently? `selectEvent` doesn't make sense for a boolean.

2017-06-30 23:26 UTC, marcusrettig commented on src/Selector.js
> +        data = selected.parent.parent.data;
`data` will be undefined here. `selected.parent` will be a planet and `selected.parent.parent` the scene.

2017-06-30 23:26 UTC, marcusrettig commented on src/Selector.js
> +        data = selected.parent.parent.data;
Please also check in the if condition that the parent is actually a planet (use `.isPlanet`).

2017-06-30 23:26 UTC, marcusrettig commented on src/ui/Crosshair.js
> +    const obj = super(geometry, material);
Why is the result of calling `super` returned?

2017-06-30 23:26 UTC, marcusrettig commented on src/ui/UI.js
> +    this.popup = new Popup('Added job!');
`'Job saved!'` better? :)

2017-06-30 23:26 UTC, marcusrettig commented on src/ui/Crosshair.js
> +  updateGeometry(size) {
Changing geometry should be avoided. Wouldn't scaling the crosshair have the save effect?

2017-06-30 23:26 UTC, marcusrettig commented on src/ui/Popup.js
> +    // TODO: Rewrite this animation using tweens.
This works for now but in the future we should use tweens for these kinds of animations. I added a todo comment to remind us.

2017-06-30 23:26 UTC, marcusrettig commented on src/ui/Crosshair.js
> +    // TODO: Rewrite this animation using tweens.
This works for now but in the future we should use tweens for these kinds of animations. I added a todo comment to remind us.

2017-06-30 23:28 UTC, marcusrettig commented on src/Selector.js
> +    }
Not clear why the above if/else blocks are needed. Could you add a comment?

2017-07-01 12:12 UTC, funrep commented on src/Selector.js
> +    }
The `selectEvent` has to be true for the next frame for it to make effect, so I used the timer convention I used elsewhere here as well, it probably makes more sense having two boolean values instead.

2017-07-01 17:55 UTC, marcusrettig approved these changes

2017-07-01 18:07 UTC, merged